name: Node

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '14', '12', '10' ]

    name: ${{ matrix.node }} (Windows)
    steps:
    - name: Configure git line-breaks
      run: git config --global core.autocrlf false
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: checkout master
      run: git branch -f master origin/master
#    - name: npm install
#      run: npm ci
#    - name: run webpack 4 tests
#      run: npm run test:v4
    - name: install webpack 5
      run: npm install webpack@^5.0.0 -D
    - name: run install again
      run: npm install
    - name: run webpack 5 tests
      run: npm run test:v5
